services:
  # web:
  #   build: .
  #   ports:
  #     - "8000:5000"
  #   # volumes:
  #   #   - .:/code
  #   #   - logvolume01:/var/log
  #   depends_on:
  #     - repo
  repo:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_PASSWORD: home-stone-groan
      POSTGRES_USER: script_runner
      POSTGRES_DB: datascrape
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U script_runner -d datascrape"]
      interval: 5s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:9.22
    depends_on:
      repo:
        condition: service_healthy
    volumes:
      - ./migrations:/flyway/sql
    command: -url=jdbc:postgresql://repo:5432/datascrape -user=script_runner -password=home-stone-groan -connectRetries=10 -baselineOnMigrate=true -locations=filesystem:/flyway/sql -validateOnMigrate=true -validateMigrationNaming=true migrate


# volumes:
#   logvolume01: {}